version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Starting build process"
      - npm run build || echo "No build script defined"
  post_build:
    commands:
      - echo "Build complete"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
